services:
  postgres:
    image: postgres:16
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s


  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    command: python main.py
    env_file: .env

    environment:
      PYTHONUNBUFFERED: "1"
      DOCKER: "True"
      PYTHONPATH: .
      DATABASE_URL: postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}                                             
    
      
    volumes:
      - ./:/Weather_API:cached
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"

  etl:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    command: python -c "from db_code.app.pipeline.etl import ETLProcess; ETLProcess(docker=True).docker_etl_background(interval_minutes=10)"
    working_dir: /Weather_API/db_code
    env_file: .env

    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: /Weather_API
      DOCKER: "True"
      DB_HOST: postgres 

    volumes:
      - ./:/Weather_API:cached
    
    depends_on:
      postgres:
        condition: service_healthy
      app:
        condition: service_started
    
volumes:
  db-data: